import { createClient } from "@supabase/supabase-js";

const supabaseUrl = "https://cvdwdjmvfaoehjkobujs.supabase.co";
const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2ZHdkam12ZmFvZWhqa29idWpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwOTQ0NTcsImV4cCI6MjA3NzY3MDQ1N30.Q36HhCG56rqOBk0PM-FEW4ExdOr5ljHb5e7j6xw3g9w";
const SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2ZHdkam12ZmFvZWhqa29idWpzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MjA5NDQ1NywiZXhwIjoyMDc3NjcwNDU3fQ.IVYk2NHkG0IjFi5NDQYO3_K5EfL5O4pruDJKo0-1Iug"
export const supabase = createClient(supabaseUrl, supabaseAnonKey);
